package liquid.objects.annotations;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

/**
 * New config system
 *
 * Usage:
 *
 * &#064;Config
 * public static boolean example = true;
 *
 * in json:
 * {
 *   "common": {
 *     "example": {
 *       "comment": "automatically generated by liquid core",
 *       "value": true
 *     }
 *   }
 * }
 *
 * Ported from fabric
 */
@Retention(RetentionPolicy.RUNTIME)
public @interface Config {
    String group() default "common";
    String comment() default "automatically generated by liquid core";
}
