package liquid.objects.block.annotations;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;
import java.lang.annotation.ElementType;

/**
 * New config system
 * <p>
 * Usage:
 * <p>
 * &#064;Config
 * public static boolean example = true;
 * <p>
 * in json:
 * <p>
 * { <p>
 *   "common": {<p>
 *     "example": {<p>
 *       "comment": "automatically generated by liquid core",<p>
 *       "value": true<p>
 *     }<p>
 *   }<p>
 * }
 *<p>
 *<p>
 * Ported from fabric
 */
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.FIELD)
public @interface Config {
    String configBranch() default "common";
    String comment() default "automatically generated by liquid core";
    String customName() default "";
}
