modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
[[mods]]
modId="liquid"
version="${file.jarVersion}"
displayName="LiquidCore"
authors="AlgorithmLX"
description='''
Little api for my mods
'''
[[dependencies.liquid]]
   modId="forge"
   mandatory=true
   versionRange="[41,)"
   ordering="NONE"
   side="BOTH"
# Here's another dependency
[[dependencies.liquid]]
   modId="minecraft"
   mandatory=true
   # This version range declares a minimum of the current minecraft version up to but not including the next major version
   versionRange="[1.19,)"
   ordering="NONE"
   side="BOTH"
